<?php

namespace Database\Seeders;

use App\Models\ChartOfAccounts;
use Illuminate\Database\Seeder;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run(): void
    {
        // Disable mass assignment protection temporarily for seeding
        ChartOfAccounts::unguard();

        // Clear existing data to prevent duplicates on re-seeding
        // ChartOfAccounts::truncate();

        // Step 1: Create top-level parent accounts
        $assets = ChartOfAccounts::create([
            'gl_code' => '1000',
            'name' => 'Assets',
            'account_type' => 'Asset',
            'description' => 'The total value of all assets owned by the SACCO.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);
        
        $liabilities = ChartOfAccounts::create([
            'gl_code' => '2000',
            'name' => 'Liabilities',
            'account_type' => 'Liability',
            'description' => 'The total financial obligations of the SACCO.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);

        $equity = ChartOfAccounts::create([
            'gl_code' => '3000',
            'name' => 'Equity',
            'account_type' => 'Equity',
            'description' => 'The members\' stake in the SACCO.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);
        
        $income = ChartOfAccounts::create([
            'gl_code' => '4000',
            'name' => 'Income',
            'account_type' => 'Income',
            'description' => 'All revenues generated by the SACCO.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);
        
        $expenses = ChartOfAccounts::create([
            'gl_code' => '5000',
            'name' => 'Expenses',
            'account_type' => 'Expense',
            'description' => 'Costs incurred in the course of SACCO operations.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);
        
        $otherIncome = ChartOfAccounts::create([
            'gl_code' => '6000',
            'name' => 'Other Income',
            'account_type' => 'Other Income',
            'description' => 'Income from non-primary business activities.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);

        $internalUse = ChartOfAccounts::create([
            'gl_code' => '7000',
            'name' => 'Internal Use',
            'account_type' => 'Internal Use',
            'description' => 'Accounts used for internal adjustments and tracking.',
            'parent_account_id' => null,
            'is_active' => true,
        ]);
        
        // Step 2: Create a sub-category and link it to its parent
        $currentAssets = ChartOfAccounts::create([
            'gl_code' => '1100',
            'name' => 'Current Assets',
            'account_type' => 'Asset',
            'description' => 'Assets expected to be converted into cash within one year.',
            'parent_account_id' => $assets->id, // Linked to the "Assets" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '1110',
            'name' => 'Cash on Hand',
            'account_type' => 'Asset',
            'description' => 'Physical cash held by the SACCO.',
            'parent_account_id' => $currentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);
        
        ChartOfAccounts::create([
            'gl_code' => '1120',
            'name' => 'Bank Account',
            'account_type' => 'Asset',
            'description' => 'Funds held in the SACCO\'s bank accounts.',
            'parent_account_id' => $currentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);

          ChartOfAccounts::create([
            'gl_code' => '1130',
            'name' => 'Member Savings Receivable',
            'account_type' => 'Asset',
            'description' => 'Money owed to the SACCO by members for savings contributions',
            'parent_account_id' => $currentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);


        ChartOfAccounts::create([
            'gl_code' => '1140',
            'name' => 'Loan Receivable - Short Term',
            'account_type' => 'Asset',
            'description' => 'Loans to be collected within one year',
            'parent_account_id' => $currentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);

          ChartOfAccounts::create([
            'gl_code' => '1150',
            'name' => 'Interest Receivable',
            'account_type' => 'Asset',
            'description' => 'Loans to be collected over a period longer than one year',
            'parent_account_id' => $currentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);

        // Step 2: Create a sub-category and link it to its parent
        $fixedAssets = ChartOfAccounts::create([
            'gl_code' => '1200',
            'name' => 'Current Assets',
            'account_type' => 'Asset',
            'description' => 'These are long-term tangible assets used in the operation of a business and not intended for sale.',
            'parent_account_id' => $assets->id, // Linked to the "Assets" parent
            'is_active' => true,
        ]);

        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '1210',
            'name' => 'Office Equipment',
            'account_type' => 'Asset',
            'description' => 'The value of office assets like computers, furniture, etc.',
            'parent_account_id' => $fixedAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);

        $nonCurrentAssets = ChartOfAccounts::create([
            'gl_code' => '1300',
            'name' => 'Non Current Assets',
            'account_type' => 'Asset',
            'description' => 'These are long-term assets not expected to be converted into cash within a year',
            'parent_account_id' => $assets->id, // Linked to the "Assets" parent
            'is_active' => true,
        ]);

        ChartOfAccounts::create([
            'gl_code' => '1310',
            'name' => 'Loan Receivable - Long Term',
            'account_type' => 'Asset',
            'description' => 'Loans to be collected over a period longer than one year.',
            'parent_account_id' => $nonCurrentAssets->id, // Linked to "Current Assets"
            'is_active' => true,
        ]);
        
        // Step 4: Continue creating all other accounts, linking them to their appropriate parents
        // Liabilities
         // Step 2: Create a sub-category and link it to its parent
        $currentLiabilities = ChartOfAccounts::create([
            'gl_code' => '2100',
            'name' => 'Current Liabilities',
            'account_type' => 'Liability',
            'description' => 'These are financial obligations of the SACCO that are due within one year.',
            'parent_account_id' => $liabilities->id, // Linked to the "Liabilites" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '2110',
            'name' => 'Accounts Payable',
            'account_type' => 'Liability',
            'description' => 'Money owed by the SACCO to vendors or creditor.',
            'parent_account_id' => $currentLiabilities->id, // Linked to "Current Liabilities"
            'is_active' => true,
        ]);

           ChartOfAccounts::create([
            'gl_code' => '2120',
            'name' => 'Member Savings Payable',
            'account_type' => 'Liability',
            'description' => 'The SACCO\'s obligation to members for their savings.',
            'parent_account_id' => $currentLiabilities->id, // Linked to "Current Liabilities"
            'is_active' => true,
        ]);

           ChartOfAccounts::create([
            'gl_code' => '2130',
            'name' => 'Deferred Income',
            'account_type' => 'Liability',
            'description' => 'This is income that has been received from a customer but has not yet been earned.',
            'parent_account_id' => $currentLiabilities->id, // Linked to "Current Liabilities"
            'is_active' => true,
        ]);

        // Non Current Liabilities

            $nonCurrentLiabilities = ChartOfAccounts::create([
            'gl_code' => '2200',
            'name' => 'Non-Current Liabilities',
            'account_type' => 'Liability',
            'description' => 'These are long-term financial obligations of the SACCO that are not due within one year.',
            'parent_account_id' => $liabilities->id, // Linked to the "Liabilites" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '2210',
            'name' => 'Loan Payable - External',
            'account_type' => 'Liability',
            'description' => 'These are long-term loans from external lenders.',
            'parent_account_id' => $nonCurrentLiabilities->id, // Linked to "Non Current Liabilities"
            'is_active' => true,
        ]);



        // Equity 

         $contributedCapital = ChartOfAccounts::create([
            'gl_code' => '3100',
            'name' => 'Contributed Equity',
            'account_type' => 'Equity',
            'description' => 'This represents the funds that members directly invest into the SACCO',
            'parent_account_id' => $equity->id, // Linked to the "equity" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '3110',
            'name' => 'Capital Contributions',
            'account_type' => 'Equity',
            'description' => 'This is the initial and ongoing capital provided by members.',
            'parent_account_id' => $contributedCapital->id, // Linked to "contributed equity"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '3120',
            'name' => 'Members Equity',
            'account_type' => 'Equity',
            'description' => 'This can be considered the total contributed capital from all members, often a summary accoun.',
            'parent_account_id' => $contributedCapital->id, // Linked to "contributed equity"
            'is_active' => true,
        ]);

        $earnedCapital = ChartOfAccounts::create([
            'gl_code' => '3200',
            'name' => 'Earned Equity',
            'account_type' => 'Equity',
            'description' => 'This represents the portion of the SACCO\'s profits that are kept and reinvested rather than distributed',
            'parent_account_id' => $equity->id, // Linked to the "equity" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '3210',
            'name' => 'Retained Earnings',
            'account_type' => 'Equity',
            'description' => 'This is the accumulation of net income that the SACCO has held onto over time..',
            'parent_account_id' => $earnedCapital->id, // Linked to "earned Equity"
            'is_active' => true,
        ]);


        $statutoryReserves = ChartOfAccounts::create([
            'gl_code' => '3200',
            'name' => 'Statutory Reserves',
            'account_type' => 'Equity',
            'description' => 'These are funds set aside for specific purposes, often mandated by legal or regulatory requirements',
            'parent_account_id' => $equity->id, // Linked to the "statutory Reserves" parent
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '3210',
            'name' => 'Statutory Reserves',
            'account_type' => 'Equity',
            'description' => 'These are reserves that are required by law or other governing bodies to ensure the SACCO\'s stability',
            'parent_account_id' => $statutoryReserves->id, // Linked to "statutory Reserves Equity"
            'is_active' => true,
        ]);


        // Income 

        $operatingIncome = ChartOfAccounts::create([
            'gl_code' => '4000',
            'name' => 'Operating Income',
            'account_type' => 'Income',
            'description' => 'Operating income is revenue generated from the core business activities of the SACCO',
            'parent_account_id' => $income->id, // Linked to operating Income"
            'is_active' => true,
        ]);
        
        // Step 3: Create accounts and link them to their parent sub-category
        ChartOfAccounts::create([
            'gl_code' => '4210',
            'name' => 'Interest Income - Loans',
            'account_type' => 'Income',
            'description' => 'This is the primary source of revenue for a lending institution like a SACCO, derived directly from its loan portfolio',
            'parent_account_id' => $operatingIncome->id, // Linked to operating Income"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '4220',
            'name' => 'Loan Processing Fees',
            'account_type' => 'Income',
            'description' => 'Fees charged for the service of processing loans are a direct result of the SACCO\'s core business operations',
            'parent_account_id' => $operatingIncome->id, // Linked to operating Income"
            'is_active' => true,
        ]);


         ChartOfAccounts::create([
            'gl_code' => '4230',
            'name' => 'Membership Fees',
            'account_type' => 'Income',
            'description' => 'The fees collected from members for their participation in the SACCO are a key part of its operational income',
            'parent_account_id' => $operatingIncome->id, // Linked to operating Income"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '4240',
            'name' => 'Penalty Income',
            'account_type' => 'Income',
            'description' => 'Income from penalties on late payments or other infractions',
            'parent_account_id' => $operatingIncome->id, // Linked to operating Income"
            'is_active' => true,
        ]);


        // Expenses
        
         $operatingExpenses = ChartOfAccounts::create([
            'gl_code' => '5000',
            'name' => 'Operating Expenses',
            'account_type' => 'Expenses',
            'description' => 'These are the costs a company incurs from its normal business operations. They\n re necessary to keep the business running.',
            'parent_account_id' => $expenses->id, // Linked to parent expenses
            'is_active' => true,
        ]);
        
        ChartOfAccounts::create([
            'gl_code' => '5210',
            'name' => 'Staff Salaries',
            'account_type' => 'Expenses',
            'description' => 'Salaries paid to Company staff',
            'parent_account_id' => $operatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '5220',
            'name' => 'Office Rent',
            'account_type' => 'Expenses',
            'description' => 'Cost of renting office space',
            'parent_account_id' => $operatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '5230',
            'name' => 'Stationery and Supplies',
            'account_type' => 'Expenses',
            'description' => 'The cost of routine office items like paper, pens, and other supplies',
            'parent_account_id' => $operatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '5240',
            'name' => 'Utilities',
            'account_type' => 'Expenses',
            'description' => 'The cost of services like electricity, water, and internet needed for the office',
            'parent_account_id' => $operatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '5250',
            'name' => 'Loan Loss Provision',
            'account_type' => 'Expenses',
            'description' => 'This is an estimated expense for loans that may not be repaid. It is a key operating expense for a lending institution, reflecting the risk inherent in its core business.',
            'parent_account_id' => $operatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);


         $nonOperatingExpenses = ChartOfAccounts::create([
            'gl_code' => '5000',
            'name' => 'Non Operating Expenses',
            'account_type' => 'Expenses',
            'description' => 'These are costs not directly related to the Company\ns primary business activities, such as lending and savings..',
            'parent_account_id' => $expenses->id, // Linked to parent expenses
            'is_active' => true,
        ]);
        
        ChartOfAccounts::create([
            'gl_code' => '5310',
            'name' => 'Interest Expense - Member Savings',
            'account_type' => 'Expenses',
            'description' => 'While related to member savings, it is considered a non-operating expense because it\ns a financial cost of borrowing funds from members, not a cost of day-to-day operations',
            'parent_account_id' => $nonOperatingExpenses->id, // Linked to operating expenses"
            'is_active' => true,
        ]);


        // Other Incomes

        $nonOperatingIncome = ChartOfAccounts::create([
            'gl_code' => '6000',
            'name' => 'Non Operating Income',
            'account_type' => 'Expenses',
            'description' => ' Revenues generated from activities outside of a company\ns primary business operations',
            'parent_account_id' => $otherIncome->id, // Linked to parent expenses
            'is_active' => true,
        ]);
        
        ChartOfAccounts::create([
            'gl_code' => '6210',
            'name' => 'Grants Received',
            'account_type' => 'Other Incomes',
            'description' => 'These are non-repayable funds received from other organizations, and they are not a result of the SACCO\ns core business of lending',
            'parent_account_id' => $nonOperatingIncome->id, // Linked to non operating other incomes"
            'is_active' => true,
        ]);

         ChartOfAccounts::create([
            'gl_code' => '6220',
            'name' => 'Donations',
            'account_type' => 'Other Incomes',
            'description' => 'donations are funds received from external sources that are not part of the SACCO\ns main financial service activitie',
            'parent_account_id' => $nonOperatingIncome->id, // Linked to non operating other incomes"
            'is_active' => true,
        ]);


        // Internal Use

          ChartOfAccounts::create([
            'gl_code' => '7000',
            'name' => 'Year-End Adjustments',
            'account_type' => 'Internal Use',
            'description' => 'Entries made at the end of a fiscal year to adjust for accruals and other items.',
            'parent_account_id' => $internalUse->id, // Linked to non operating other incomes"
            'is_active' => true,
        ]);


        
        
        // Re-enable mass assignment protection
        ChartOfAccounts::reguard();
    }

}
